### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by JebKlob6** [buks-dikeocha/TTP-Assignment1#1]
Brief Background behind idea 
Car company showing the benefits of electric cars compared to gas 

What we need 
Home page      - which shows different model of cars and a brief description on gas and electric cars
resource page - with us as contributors explaining the company goals and future 
About page      - lastly a page where we discuss the benefits of electric cars on the consumer and the environment.

**Comment by JebKlob6** [comment]
Resource Page

**Comment by Bhavyapb** [comment]
working on about page

**Comment by buks-dikeocha** [comment]
finished resource page and about page, skipped home page for now

**Comment by buks-dikeocha** [comment]
home page added and working
